### ISSUE TITLE
clusterSingleBatches crashes

### ISSUE THREAD

**Issue by liadJB** [MouseLand/Kilosort2#12]
When running kilosort on a 32 channel recording W0 in clusterSingleBatches is not defined.

It's because this line: W0 = gpuArray.zeros(nPCs, NchanNear, Nfilt, 'single');
only happens if size(uproj,2)>=Nfilt

and this [uproj, call] = extractPCbatch2(rez, wPCA, min(nBatches-1, ibatch), iC);   produces a 51X11 uproj matrix.

Have you got any ideas why that might happen? I left the configuration as it is.

Thanks!

**Comment by marius10p** [comment]
I will fix this bug, but it indicates that you had a 2s batch with fewer than 16 threshold crossings. Is that what you'd expect? You can also try to lower the threshold crossing threshold ops.ThPre. That is only used for the batch re-ordering step. If you don't get enough spikes, there won't be enough information in a single batch to determine drift. Another solution could be to increase the batch size. 

Another possibility is that the data is not correctly recognized, and that's why it doesn't find the threshold crossings. Are you running from the kilosort GUI? If so, does it look like your data is correctly loaded and filtered?

**Comment by marius10p** [comment]
Pushed the bug fix.

**Comment by liadJB** [comment]
Hi Marius,

Thanks for the fix. I'll give it a go now.
Funnily enough I would expect it. Some of the animals I'm using are neonates, and in them sometimes it can even be 30 seconds or more with no apparent activity.

**Comment by liadJB** [comment]
Hi Marius it still crashes down stream because there are 0 values as indices there:

**Comment by marius10p** [comment]
I fixed the bug by replacing those default values with 1. 

If you have relatively few spikes per batch, it will work better to increase the size of the batch (ops.NT), for example to 30s (but it always has to be multiple of 32 + ntbuff). As a consequence, you would only be able to correct drift on that slower timescale. If we don't see spikes, we cannot tell if they are shifted or not, so you have to find the minimum timescale over which drift correction works for you.

**Comment by liadJB** [comment]
Thanks! I'll give it a go.
I understand. I suppose that's just a tradeoff I need to bear in mind. I suppose my strategy should be to roughly estimate the time between quiet periods and try to get the minimum batch size that's bigger than that number.

Cheers!

**Comment by liadJB** [comment]
Thank for trying to fix it.....howwever, it's still crashing :/

Error using gpuArray/eig
Input matrix contains NaN or Inf.

Error in svdecon (line 23)
    [U,D] = eig(C);

Error in sortBatches2 (line 7)
[u, s, v] = svdecon(ccb0);

Error in clusterSingleBatches (line 150)
[ccb1, iorig] = sortBatches2(ccb0);

Error in MasterKiloSortLJB (line 59)
rez = clusterSingleBatches(rez);

Is there any way to maybe bypass the drift correction? or do it partially, without disturbing the rest of the sorting process? 
It's just that for the young animals it will always be the case of having more than 30 seconds periods and not many spikes in general.

Thanks a  lot!

**Comment by marius10p** [comment]
I added an option to disable batch reordering. Set ops.reordering = 0. 

What did you set ops.NT to? If you do need drift correction, and depending how long your recordings are, you can even set ops.NT to minutes.

**Comment by liadJB** [comment]
I set it to  512*1024+ ops.ntbuff. I suppose I can try to make it even
longer than that too then.
I'll try the fix too, but I suppose slow drift correction is better than
nothing.

**Comment by marius10p** [comment]
Slow timescale drift correction is often sufficient, and you would also get that by turning off the re-ordering: you then get tracking across time, rather than across the re-ordered batches. The rest of the algorithm may be robust enough to handle fast timescale drift (basically treats it as noise, or amplitude variation), but it depends on your preparation / implant.

**Comment by liadJB** [comment]
Great!
Thank you very much. I actually made it run over 8 seconds and it seems to
be good enough.
Thanks very much for the fixes!

**Comment by liadJB** [comment]
Hi Marius,

Worked with kilosort some more with really young animals. Now when I try to increase the bath size to about one minute I get this error when trying to fit templates:

In an assignment  A(:) = B, the number of elements in A and B must be the same.

Error in triageTemplates2 (line 12)
ndrop(1) = .9 * ndrop(1) + .1*gather(sum(idrop));

Error in learnAndSolve8b (line 188)
                triageTemplates2(ops, iW, C2C, W, U, dWU, mu, nsp, ndrop);

Error in MasterKiloSortLJB (line 62)
rez = learnAndSolve8b(rez);

Due to ndrop being 1X2 and idrop 9x9.

strangely in another animal if I made the interval shorter it worked again.

**Comment by liadJB** [comment]
Correction: When I run it with a shorter time period even with ops.reordering = 0;

I'm getting the following error: 

Error using randperm
K must be less than or equal to N.

Error in extractTemplatesfromSnippets (line 53)
wTEMP = dd(:, randperm(size(dd,2), nPCs));

Error in learnAndSolve8b (line 9)
[wTEMP, wPCA]    = extractTemplatesfromSnippets(rez, NrankPC);

Error in MasterKiloSortLJB (line 62)
rez = learnAndSolve8b(rez);

dd is 64X2 and nPCS = 6;

**Comment by marius10p** [comment]
That is probably because I skip every 100 batches to extract spikes for computing PCs. I added an option nskip to modify this behavior, and set its default to 25 instead of 100. Maybe you should try 5 or less.

**Comment by marius10p** [comment]
idrop should be a vector, not a matrix. Can you track it back to see why it becomes a matrix? Is amax a matrix? If so, what size is ipair?

**Comment by liadJB** [comment]
Yes I'll track it! So far I managed to find a set of configurations that
run pretty well in terms of detection.
But for the sake of debugging I'll try to properly track idrop!

**Comment by NoahDolev** [comment]
@liadJB How did you manage to solve this issue? Can you post your "set of configurations"?

**Comment by liadJB** [comment]
Hi Noah,

These are the configuration I'm using now:

ops.spkTh           = -4;      % spike threshold in standard deviations (-6)

ops.GPU                 = 1; % has to be 1, no CPU version yet, sorry
ops.Nfilt               = 64; % max number of clusters
ops.nfilt_factor        = 3; % max number of clusters per good channel
(even temporary ones)
ops.ntbuff              = 64;    % samples of symmetrical buffer for
whitening and spike detection
ops.NT                  = 6*32*1024+ ops.ntbuff; % must be multiple of 32 +
ntbuff. This is the batch size (try decreasing if out of memory).
ops.whiteningRange      = 32; % number of channels to use for whitening
each channel
ops.nSkipCov            = 25; % compute whitening matrix from every N-th
batch
ops.scaleproc           = 200;   % int16 scaling of whitened data
ops.nPCs                = 3; % how many PCs to project the spikes into
ops.useRAM              = 0; % not yet available
